services:
  web:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/geolocations_development
    depends_on:
      - db
    volumes:
      - .:/rails
      - bundle_data:/usr/local/bundle

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=geolocations_development
    ports:
      - '5432:5432'

volumes:
  postgres_data:
  bundle_data:
